on:
  pull_request:
    types:
      - closed
    branches:
      - 'release/**'

jobs:
  create_request:
    runs-on: ubuntu-latest

    if: github.event.pull_request.merged == true
  
    permissions:
      pull-requests: wirte
    
    steps:
      - name: Create PR
        run: |
          gh pr create -B base_branch -H branch_to_merge --title 'Merge branch_to_merge into base_branch' --body 'Created by Github action'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
