name: Create Pull Request to develop

on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
      - 'release/**'

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up GitHub CLI
        uses: actions/setup-gh@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Pull Request to develop
        run: |
          SOURCE_BRANCH="${{ github.head_ref }}"
          TARGET_BRANCH="develop"

          gh pr create --head "$SOURCE_BRANCH" --base "$TARGET_BRANCH" --title "Merge $SOURCE_BRANCH into develop" --body "This is an automated PR to merge $SOURCE_BRANCH into develop."
